services:

  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!password
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: pg!password

      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "4321:80"
    depends_on:
      - postgres

  app:
    build:
      context: .
    ports:
      - "8001:80"
    volumes:
      - ./storage/app/public:/var/www/storage/app/public
    depends_on:
      - postgres
    environment:
      APP_ENV: production
      APP_KEY: base64:your-app-key
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: lbaw24155
      DB_USERNAME: postgres
      DB_PASSWORD: pg!password